language: go

go:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - tip


services:
    - mongodb

before_script:
    - go run ./src/main.go
    - sleep 5 # give some time to start

script: go test -v ./...
