language: go

go:
    - 1.2
    - 1.3
    - tip

before_install:
    - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.12.zip -O go_appengine.zip -nv
    - unzip -q go_appengine.zip
    - ln -s go_appengine/goroot/src/pkg/appengine $GOPATH/src/appengine

install:
    - cd src
    - go get -d -v ./... && go build -v ./...
    - cd ..

before_script:
    - cd src
    - ./go_appengine/goapp serve &
    - cd ..
    - sleep 5 # give some time to start

script:
    - go test -v ./src/...
