language: go

go:
    - 1.2

install:
    - go get -d -v ./src && go build -v ./src

services:
    - mongodb

before_script:
    - go run ./src/main.go
    - sleep 5 # give some time to start

script:
    - go test -v ./src/...
