language: go
sudo: false # enforced for educational pack anyway, just making it clear

go:
    - 1.2

# Setup GAE and start Xvfb
before_install:
    - bash ./scripts/setup_gae.sh
    - export PATH="$PATH:$(pwd)/go_appengine"
    - sh -e /etc/init.d/xvfb start # start xvfb
    - export DISPLAY=:99.0 # set xvfb display
    - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar # get selenium standalone
    - java -jar selenium-server-standalone-2.43.1.jar > /dev/null & # run selenium server
    - pip install --user selenium # install python selenium package
    - setxkbmap us # prevents python selenium from garbling special chars if xkbmap != us
    - npm install
    - gulp build # run gulp

install:
    - cd src
    - goapp get -d -v ./... && goapp build -v ./...
    - cd ..

before_script:
    - cd src/app
    - goapp serve &
    - cd ../..
    - sleep 5 # give some time to start

script:
    - goapp test -v -cover ./src/...
    - python -m unittest discover -s ./tests/dist -p '*.py'
