language: go

go:
    - 1.2
   #- 1.3
   #- tip

before_install:
    - bash ./scripts/setup_gae.sh

install:
    - cd src
    - ../go_appengine/goapp get -d -v ./... && ../go_appengine/goapp build -v ./...
    - cd ..

before_script:
    - cd src/app
    - ../../go_appengine/goapp serve &
    - cd ../..
    - sleep 5 # give some time to start

script:
    - ./go_appengine/goapp test -v -cover ./src/...
