language: go

go:
    - 1.2
    - 1.3

install:
    - cd src
    - go get -d -v && go build -v

services:
    - mongodb

before_script:
    - go run ./src/main.go
    - sleep 5 # give some time to start

script:
    - go test -v ./src/...
