language: go

go:
    - 1.2

before_install:
    - bash ./scripts/setup_gae.sh
    - export PATH="$PATH:$(pwd)/go_appengine"

install:
    - cd src
    - goapp get -d -v ./... && goapp build -v ./...
    - cd ..

before_script:
    - cd src/app
    - goapp serve &
    - cd ../..
    - sleep 5 # give some time to start

script:
    - goapp test -v -cover ./src/...
