language: go

go:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - tip

install:
    - cd src
    - go get -d -v ./... && go build -v ./...
    - cd ..

services:
    - mongodb

before_script:
    - go run ./src/main.go &
    - sleep 5 # give some time to start

script:
    - go test -v ./src/...
