application: futarchio
version: 0
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
#  secure: always

- url: /apidocs.*
  script: _go_app
#  secure: always

- url: /
  static_files: site/dist/index.html
  upload: site/dist/index.html
#  secure: always

- url: /
  static_dir: site/dist
#  secure: always
